### ISSUE TITLE
Commit 43ed7d4785011fa40461805566ef48db222f2bc8 breaks chart when using custom Jenkins images

### ISSUE THREAD

**Issue by nabz09** [jenkinsci/helm-charts#615] opened 2022-04-24 11:19 UTC
### Describe the bug

The commit adds a dependency on the controller.tag property being a valid Semantic Version, so setting tag to "latest" will not allow the chart to deploy.

 Also the chart version must match the version of the controller Jenkins image otherwise the logic added in the commit will not operate as expected.

The logic causing this is added here: https://github.com/jenkinsci/helm-charts/blame/main/charts/jenkins/templates/_helpers.tpl#L117

### Version of Helm and Kubernetes

```markdown
- Helm: v3.5.4
- Kubernetes: 1.15.1
```

### Chart version

3.12.0

### What happened?

```bash
1. Create a values.yml file which sets the controller.image and controller.tag to be a custom Jenkins image where the tag does not follow SemVer, e.g tag set to latest
2. Attempting to install the Helm chart with this Values.yml produces the error: 

Error: UPGRADE FAILED: template: jenkins/templates/jcasc-config.yaml:43:8: executing "jenkins/templates/jcasc-config.yaml" at <include "jenkins.casc.defaults" .>: error calling include: template: jenkins/templates/_helpers.tpl:117:28: executing "jenkins.casc.defaults" at <semver (default .Chart.AppVersion .Values.controller.tag)>: error calling semver: Invalid Semantic Version
```

### What you expected to happen?

Helm chart should install without error

### How to reproduce it

```markdown
1. Create a values.yml file which sets the controller.image and controller.tag to be a custom Jenkins image where the tag does not follow SemVer, e.g tag set to latest
2. Attempting to install the Helm chart with this Values.yml produces an error: helm install my-release jenkins/jenkins -f values.yml
```

**Comment by michalmagun** [comment] 2022-05-13 07:44
Same as #592

**Comment by timja** [comment] 2022-05-13 12:00
Duplicate of https://github.com/jenkinsci/helm-charts/issues/592

**Closed by timja** 2022-05-13 12:00 UTC
Labels: bug
